name: 'Printer'
description: 'A simple GitHub Action to print messages'
inputs:
  message:
    description: 'Message to print'
    required: true
    default: 'Hello, World!'
runs:
  using: 'node12'
  main: 'index.js'
