name: 'Printer Action'
description: 'A custom action to print something'
runs:
  using: 'composite'
  steps:
    - run: echo "Printing something..."
      shell: bash
    - run: echo 'Mani is doing this action manually'
      shell: bash
