name: Job 2 Workflow

on:
  workflow_call:
    inputs:
      param2:
        required: false
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Job 1
        run: echo "job 2 runner"
