name: Test xvfb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test-xvfb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run script with xvfb
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" bash -c 'echo "Hello, World!" && sleep 5'
