name: practice-workflow

on:
    workflow_dispatch

jobs:
    echo-something:
        runs-on: ubuntu-latest
        steps:
          - name: echo-some-item
            run: echo 'all_done_with hand'
