name: CI

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/my-custom-action
        with:
          input-name: 'my-value'

      - name: Run custom action
        uses: ./.github/actions/printer
