name: Debug Environment Variable

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Environment Variable
      run: echo "this is env : ${{ env.MANI }}"

