name: practice-workflow

on:
    [workflow_dispatch,push]

jobs:
    echo-something:
        runs-on: ubuntu-latest
        steps:
          - name: echo-some-item
            run: echo 'all_done_with hand'
          - name: printer
            uses: ./.github/actions/printer