name: composite acions learn

on: [push]

jobs:
    echo-something:
        runs-on: ubuntu-latest
        steps:
          - name: echo-some-item
            run: echo 'all_done_with hand'
          - name: checkout repo
            uses: actions/checkout@v2
          - name: printer
            uses: ./.github/actions/printer/action.yml
