name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  use-reusable-workflow:
    uses: ./.github/workflows/reuse.yml
    with:
      node-version: '16'
      test-command: 'this is passed reuse'
