name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files
        run: ls -R .github/actions

      - name: Run Job 1
        uses: ./.github/actions/job1
        with:
          param1: "Hello from Job 1"

      - name: Run Job 2
        uses: ./.github/actions/job2
        with:
          param2: "Hello from Job 2"
