name: CI Reusable Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        type: string
      test-command:
        description: 'Command to run tests'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: pass something
        run: echo ${{ inputs.node-version }} is the node version

      - name: Run tests
        run: ${{ inputs.test-command }}
